unit frmImpressao_GeraisOP_DMI;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics, Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls, Vcl.ExtCtrls,
  ppComm, ppRelatv, ppProd, ppClass, ppReport, ppCtrls, ppPrnabl, ppBands, ppCache, ppDesignLayer, ppParameter, Data.DB, MemDS, DBAccess, MSAccess, ppDB, ppDBPipe, 
  ppStrtch, ppSubRpt, Funcoes, RxCtrls, RxLookup, IniFiles, ppMemo;

type
  TImpressao_GeraisOP_DMI = class(TForm)
    rDMI: TppReport;
    Panel1: TPanel;
    bSair: TButton;
    bImprimir: TButton;
    ppParameterList1: TppParameterList;
    ppDesignLayers1: TppDesignLayers;
    ppDesignLayer1: TppDesignLayer;
    ppDetailBand1: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppDBText1: TppDBText;
    pEmpresas: TppDBPipeline;
    tEmpresas: TMSQuery;
    dstEmpresas: TMSDataSource;
    tDMI: TMSQuery;
    dstDMI: TMSDataSource;
    pDMI: TppDBPipeline;
    pIE1: TppDBText;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    tNCM: TMSQuery;
    dstNCM: TMSDataSource;
    pNCM: TppDBPipeline;
    NCM: TppSubReport;
    ppChildReport1: TppChildReport;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppDetailBand2: TppDetailBand;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppLabel1: TppLabel;
    ppDBText13: TppDBText;
    ppLabel2: TppLabel;
    ppShape1: TppShape;
    ppShape2: TppShape;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppLine3: TppLine;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppShape3: TppShape;
    ppLabel12: TppLabel;
    ppLine4: TppLine;
    ppLine5: TppLine;
    ppLabel13: TppLabel;
    ppLine6: TppLine;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLine7: TppLine;
    ppLine8: TppLine;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLine9: TppLine;
    ppLabel20: TppLabel;
    ppLabel21: TppLabel;
    ppShape4: TppShape;
    ppLabel22: TppLabel;
    ppLine10: TppLine;
    ppLine11: TppLine;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppShape5: TppShape;
    ppLabel25: TppLabel;
    ppLine12: TppLine;
    ppLabel26: TppLabel;
    ppLine13: TppLine;
    ppLabel27: TppLabel;
    ppLine14: TppLine;
    ppLine15: TppLine;
    ppLabel28: TppLabel;
    ppLine16: TppLine;
    ppLine17: TppLine;
    ppLine18: TppLine;
    ppLine19: TppLine;
    ppLabel29: TppLabel;
    ppLabel30: TppLabel;
    ppLabel31: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppLine20: TppLine;
    ppShape6: TppShape;
    ppLine21: TppLine;
    ppLine22: TppLine;
    ppDBText10: TppDBText;
    ppLabel34: TppLabel;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppLabel35: TppLabel;
    ppShape7: TppShape;
    ppLabel36: TppLabel;
    ppTitleBand1: TppTitleBand;
    ppSummaryBand1: TppSummaryBand;
    ppShape8: TppShape;
    ppLine23: TppLine;
    ppLabel37: TppLabel;
    ppLine24: TppLine;
    ppLabel38: TppLabel;
    ppLine25: TppLine;
    ppLabel39: TppLabel;
    ppLine26: TppLine;
    ppDBText16: TppDBText;
    ppLabel40: TppLabel;
    ppDBText17: TppDBText;
    ppLine27: TppLine;
    ppLabel41: TppLabel;
    ppDBText18: TppDBText;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    ppLabel44: TppLabel;
    ppDBText19: TppDBText;
    ppLabel45: TppLabel;
    ppDBText20: TppDBText;
    ppLine28: TppLine;
    ppLabel46: TppLabel;
    ppLabel47: TppLabel;
    ppDBText21: TppDBText;
    ppLabel48: TppLabel;
    ppDBText22: TppDBText;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppDBText23: TppDBText;
    ppLine29: TppLine;
    ppLabel51: TppLabel;
    ppDBText24: TppDBText;
    ppLabel52: TppLabel;
    ppLabel53: TppLabel;
    ppDBText25: TppDBText;
    ppLine30: TppLine;
    ppLabel54: TppLabel;
    ppDBText26: TppDBText;
    ppLabel55: TppLabel;
    ppLabel56: TppLabel;
    ppDBText27: TppDBText;
    ppLine31: TppLine;
    ppLabel57: TppLabel;
    ppDBText28: TppDBText;
    ppLabel58: TppLabel;
    ppLabel59: TppLabel;
    ppDBText29: TppDBText;
    ppLine32: TppLine;
    ppLabel60: TppLabel;
    ppDBText30: TppDBText;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppDBText31: TppDBText;
    ppLine33: TppLine;
    ppLabel63: TppLabel;
    ppDBText32: TppDBText;
    ppLabel64: TppLabel;
    ppLabel65: TppLabel;
    ppDBText33: TppDBText;
    ppLine34: TppLine;
    ppLine35: TppLine;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppDBText34: TppDBText;
    ppLine36: TppLine;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppDBText35: TppDBText;
    ppLine37: TppLine;
    ppLabel70: TppLabel;
    ppLabel71: TppLabel;
    ppDBText36: TppDBText;
    ppLine38: TppLine;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    ppDBText37: TppDBText;
    ppLine39: TppLine;
    ppDBText38: TppDBText;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppDBText39: TppDBText;
    ppLine40: TppLine;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppDBText40: TppDBText;
    ppLine41: TppLine;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppDBText41: TppDBText;
    ppLine42: TppLine;
    ppDBText42: TppDBText;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppDBText43: TppDBText;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppShape9: TppShape;
    ppLine43: TppLine;
    ppLabel84: TppLabel;
    ppLine44: TppLine;
    lData: TppLabel;
    ppLine45: TppLine;
    ppLabel85: TppLabel;
    rGLME: TppReport;
    ppDetailBand3: TppDetailBand;
    ppShape14: TppShape;
    ppDBText44: TppDBText;
    ppSubReport1: TppSubReport;
    ppChildReport2: TppChildReport;
    ppDetailBand4: TppDetailBand;
    ppShape16: TppShape;
    ppDBText53: TppDBText;
    ppDBText55: TppDBText;
    ppSummaryBand2: TppSummaryBand;
    ppDBText58: TppDBText;
    ppLabel94: TppLabel;
    ppLine67: TppLine;
    ppLine68: TppLine;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppLabel138: TppLabel;
    ppLabel139: TppLabel;
    ppLabel140: TppLabel;
    ppLine69: TppLine;
    ppLine70: TppLine;
    ppLine71: TppLine;
    ppLabel141: TppLabel;
    ppLabel171: TppLabel;
    ppFooterBand2: TppFooterBand;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppParameterList2: TppParameterList;
    ppLine91: TppLine;
    ppLine72: TppLine;
    ppLine73: TppLine;
    ppLabel142: TppLabel;
    ppLabel143: TppLabel;
    ppLine74: TppLine;
    ppLabel144: TppLabel;
    ppDBText45: TppDBText;
    ppLine75: TppLine;
    ppDBText46: TppDBText;
    ppLine76: TppLine;
    ppLine77: TppLine;
    ppLabel145: TppLabel;
    ppLine78: TppLine;
    pIE2: TppDBText;
    ppLabel146: TppLabel;
    ppDBText48: TppDBText;
    ppLine79: TppLine;
    ppLabel147: TppLabel;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppLine80: TppLine;
    ppLabel148: TppLabel;
    ppDBText51: TppDBText;
    ppLine81: TppLine;
    ppLabel149: TppLabel;
    ppDBText52: TppDBText;
    ppLabel150: TppLabel;
    ppLine82: TppLine;
    ppLabel151: TppLabel;
    ppLine83: TppLine;
    ppDBText84: TppDBText;
    ppDBText85: TppDBText;
    ppLabel152: TppLabel;
    ppDBText86: TppDBText;
    ppLabel153: TppLabel;
    ppDBText87: TppDBText;
    ppLabel154: TppLabel;
    ppLine84: TppLine;
    ppLine85: TppLine;
    ppLine86: TppLine;
    ppLine87: TppLine;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel157: TppLabel;
    ppLine88: TppLine;
    ppLabel158: TppLabel;
    ppLabel159: TppLabel;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppLine89: TppLine;
    ppLine90: TppLine;
    ppLine92: TppLine;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText91: TppDBText;
    ppLine93: TppLine;
    ppLabel162: TppLabel;
    ppLine94: TppLine;
    ppLine95: TppLine;
    ppLine96: TppLine;
    ppLine97: TppLine;
    ppLine98: TppLine;
    ppLine99: TppLine;
    ppLabel163: TppLabel;
    ppLabel164: TppLabel;
    ppLabel165: TppLabel;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppLabel169: TppLabel;
    ppDBText92: TppDBText;
    ppLine100: TppLine;
    ppDBText93: TppDBText;
    ppDBText94: TppDBText;
    ppLabel168: TppLabel;
    ppDBText95: TppDBText;
    ppDBText96: TppDBText;
    ppDBText97: TppDBText;
    ppLine101: TppLine;
    ppLine102: TppLine;
    ppLabel170: TppLabel;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppLine104: TppLine;
    ppLabel86: TppLabel;
    ppLine103: TppLine;
    ppLabel174: TppLabel;
    ppLine105: TppLine;
    ppLabel175: TppLabel;
    ppLine106: TppLine;
    ppLabel176: TppLabel;
    ppLine107: TppLine;
    ppLine108: TppLine;
    ppDBText98: TppDBText;
    ppLine109: TppLine;
    ppLine110: TppLine;
    ppShape10: TppShape;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLine46: TppLine;
    ppDBText56: TppDBText;
    ppLabel89: TppLabel;
    ppDBText57: TppDBText;
    lEndereco: TppLabel;
    lEndereco2: TppLabel;
    ppLabel90: TppLabel;
    ppLine47: TppLine;
    ppLabel91: TppLabel;
    ppLine48: TppLine;
    ppLabel92: TppLabel;
    ppLabel93: TppLabel;
    ppLabel95: TppLabel;
    ppLine49: TppLine;
    ppLine50: TppLine;
    ppLine51: TppLine;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    cDMI: TCheckBox;
    cGLME: TCheckBox;
    cDI: TRxDBLookupCombo;
    StaticText7: TStaticText;
    Image1: TImage;
    RxLabel2: TRxLabel;
    RxLabel1: TRxLabel;
    tDI: TMSQuery;
    dstDI: TMSDataSource;
    tDIDI: TStringField;
    ppDBText2: TppDBText;
    ppDBText47: TppDBText;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppLine52: TppLine;
    ppDBMemo1: TppDBMemo;
    procedure bSairClick(Sender: TObject);
    procedure bImprimirClick(Sender: TObject);
    procedure rDMIBeforePrint(Sender: TObject);
    procedure ppSummaryBand2BeforePrint(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Impressao_GeraisOP_DMI: TImpressao_GeraisOP_DMI;

implementation

{$R *.dfm}

uses frmMenu_Principal, frmDados;

procedure TImpressao_GeraisOP_DMI.bImprimirClick(Sender: TObject);
begin
     with tEmpresas do begin
          sql.Clear;
          sql.add('select CNPJ');
          sql.add('      ,Razao_Social = upper(Razao_Social)');
          sql.add('      ,Estado');
          sql.add('      ,Estado_Nome = (select upper(Nome) from Cybersoft_Cadastros.dbo.Estados where Codigo = Estado)');
          sql.add('      ,IE');
          sql.add('      ,CEP');
          sql.add('      ,Rua = upper(Rua)');
          sql.add('      ,Rua_Numero');
          sql.add('      ,Complemento = upper(Complemento)');
          sql.add('      ,Bairro = upper(Bairro)');
          sql.add('      ,Municipio_Nome = (select upper(Nome) from Cybersoft_Cadastros.dbo.Municipios where Codigo = Municipio_Codigo)');
          sql.add('      ,CNAE');
          sql.add('      ,Telefone = Telefone1');
          sql.add('      ,Representante_Nome');
          sql.add('      ,Representante_CNPJ_CPF = isnull(Representante_CNPJ, '''') + isnull(Representante_CPF, '''')');
          sql.add('      ,Representante_Rua');
          sql.add('      ,Representante_Numero');
          sql.add('      ,Representante_Bairro');
          sql.add('      ,Representante_Estado');
          sql.add('      ,Representante_Telefone');
          sql.add('      ,Representante_Email');
          sql.add('      ,Representante_Complemento');
          sql.add('      ,Representante_Municipio = (select Nome from Municipios where Codigo = Representante_Municipio)');
          sql.add('from Cybersoft_Cadastros.dbo.Empresas ');
          sql.add('where Codigo = :pEmpresa');
          parambyname('pEmpresa').AsInteger := Menu_Principal.mEmpresa;
          open;
     end;
     with Dados, IncentivosFiscais do begin
          sql.Clear;
          sql.Add('select *');
          sql.Add('from IncentivosFiscais');
          sql.Add('where Estado = :pEstado');
          parambyname('pEstado').AsString := tEmpresas.FieldByName('Estado').AsString;
          open;
     end;

     with tDMI do begin
          sql.Clear;
          sql.add('select Numero_Declaracao');
          sql.Add('      ,Data_RegistroDeclaracao');
          sql.Add('      ,UF_Desembaraco');
          sql.add('      ,Peso_Liquido');
          sql.add('      ,Peso_Bruto');
          sql.add('      ,Taxa_FOB');
          sql.add('      ,Numero_Fatura = ltrim(rtrim(Numero_Fatura))');
          sql.add('      ,Via_Transporte = (select Descricao from Cybersoft_Cadastros.dbo.ViaTransporte vt where vt.Codigo = pd.Via_Transporte)');
          sql.add('      ,CE = ltrim(rtrim(Numero_DOC))');
          sql.add('      ,Pais_Procedencia = (select ltrim(rtrim(Nome)) from Cybersoft_Cadastros.dbo.Paises pa where pa.Codigo = pd.Codigo_PaisOrigem)');
          sql.add('      ,Data_Entrada = Data_DesembaracoDeclaracao');
          sql.add('      ,Aliquota_Interna = (select ICMS_Interno from ICMS where UF = :pUF)');
          sql.add('      ,Aliquota_Interestadual = (select max(Aliquota_ICMSOper) from NotasItens ni where ni.DI = :pDI)');
          sql.add('      ,Valor_Importacao = isnull(FOB, 0)+isnull(Seguro, 0) + isnull(Frete, 0)');
          sql.add('      ,II = isnull(II, 0)');
          sql.add('      ,IPI = isnull(Valor_IPI, 0)');
          sql.add('      ,PIS = isnull(Valor_PIS, 0)');
          sql.add('      ,COFINS = isnull(Valor_COFINS, 0)');
          sql.add('      ,Despesas = (select sum(isnull(Valor_Parcela, 0)) from PagarReceber pr where pr.Tipo = ''P'' and isnull(pr.Custo_Entrada, 0) = 1 and pr.Processo IN(select Processo from ProcessosDocumentos where Numero_Declaracao = :pDI))');
          sql.add('      ,BCICMS_Entrada = cast(0 as money)');
          sql.add('      ,ICMS_Entrada = cast(0 as money)');
          sql.add('      ,ICMS = ''DIFERIDO'' ');
          sql.add('      ,BCICMS_Saida = cast(0 as money)');
          sql.add('      ,BCICMS_Reducao = cast(0 as money)');
          sql.add('      ,BCICMS_Ajustada = cast(0 as money)');
          sql.add('      ,ICMS_Aliquota = cast(0 as float)');
          sql.add('      ,ICMS_Aliquota_Valor = (select sum(Valor_ICMSOper) from NotasItens ni where ni.DI = pd.Numero_Declaracao)');
          sql.add('      ,ICMS_Cred_Pres = cast(0 as money)');
          sql.add('      ,ICMS_Devido = (select sum(Valor_ICMSOper) from NotasItens ni where ni.DI = pd.Numero_Declaracao)');
          sql.add('      ,ICMS_Pago_Aliquota = cast(0 as float)');
          sql.add('      ,ICMS_Pago_Valor = cast(0 as money)');
          sql.add('      ,ICMS_Grafica = (select sum(Valor_ICMSOper) from NotasItens ni where ni.DI = pd.Numero_Declaracao)');
          sql.Add('      ,Total = cast(0 as money)');
          sql.add('      ,Identificacao = '''' ');
          sql.Add('      ,Adquirente = (select Nome from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_IE = (select Inscricao_Estadual from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_CNPJ = (select CNPJ from Clientes cli where Codigo = pd.Cliente)');
          sql.add('      ,Adquirente_CNAE = (select CNAE from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Rua = (select Rua from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_CEP = (select CEP from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Estado = (select Estado from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Bairro = (select Bairro from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Municipio = (select Municipio from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Telefone = (select Telefone1 from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Adquirente_Email = (select Email from Clientes cli where Codigo = pd.Cliente)');
          sql.Add('      ,Recinto_Alfandegario');
          sql.Add('      ,Recinto_AlfandegarioCod');
          sql.Add('      ,Trantamento_Tributario = '''' ');
          sql.Add('      ,Fundamento_Legal = (select ltrim(rtrim(cast(icf.Fundamento_Legal as varchar(500)))) from Cybersoft_Cadastros.dbo.IncentivosFiscais icf where icf.Estado = :pUF)');
          sql.Add('      ,Codigo_TratamentoTrib = (select icf.Codigo_TratamentoTrib from Cybersoft_Cadastros.dbo.IncentivosFiscais icf where icf.Estado = :pUF)');
          sql.Add('into #temp');
          sql.add('from ProcessosDocumentos pd');
          sql.add('where pd.Numero_Declaracao = :pDI');
          sql.Add('update #Temp set Total = Valor_Importacao + II + IPI + PIS + COFINS + Despesas');
          sql.Add('update #Temp Set BCICMS_Entrada  = Total/((100-Aliquota_Interna)/100.)');
          sql.Add('                ,BCICMS_Ajustada = Total/((100-Aliquota_Interna)/100.)');
          sql.add('select * from #temp');
          sql.Add('drop table #temp');
          parambyname('pDI').asstring := tDI.FieldByName('DI').AsString;
          parambyname('pUF').asstring := tEmpresas.FieldByName('Estado').AsString;
          //sql.SaveToFile('c:\temp\Impressao_DMI.sql');
          open;
     end;
     with tNCM do begin
          sql.Clear;
          sql.add('select distinct Adicao');
          sql.add('      ,NCM');
          sql.add('      ,NCM_Descricao = (select Produto from NCM nc where nc.NCM = ad.NCM)');
          sql.Add('      ,Tratamento_TribICMS = (select Tratamento_TribICMS from NCM nc where nc.NCM = ad.NCM)');
          sql.Add('      ,Valor_Aduaneiro = (select sum(round(Valor_UnitarioReal * Quantidade, 2)) from Adicoes ad2 where ad2.DI = :pDI and ad2.NCM = ad.NCM)');
          sql.add('from Adicoes ad');
          sql.add('where DI = :pDI');
          sql.Add('order by Adicao, NCM');
          parambyname('pDI').asstring := tDI.FieldByName('Di').AsString;
          open;
     end;
     with Dados.Estados do begin
          sql.Clear;
          sql.Add('select *');
          sql.Add('from Estados');
          sql.Add('where Codigo = :pUF');
          Parambyname('pUF').AsString := tEmpresas.FieldByName('Estado').AsString;
          open;
          pIE1.DisplayFormat := FieldByName('Mascara_Inscricao').AsString;
          pIE2.DisplayFormat := FieldByName('Mascara_Inscricao').AsString;
     end;

     if cDMI.Checked then begin
        rDMI.Print;
        rDMI.Reset;
     end;
     if cGLME.Checked then begin
        rGLME.Print;
        rGLME.Reset;
     end;
end;

procedure TImpressao_GeraisOP_DMI.bSairClick(Sender: TObject);
begin
    close;
end;

procedure TImpressao_GeraisOP_DMI.FormClose(Sender: TObject; var Action: TCloseAction);
var
   aINI: TIniFile;
begin
      aINI := TIniFile.Create(ExtractFilePath(Application.ExeName)+'ImportaRelatorios.ini');
      aINI.WriteString ('IMPRESSAO_DMI_GKME', 'DI'  , tDI.fieldbyname('DI').AsString);
      aINI.WriteBool   ('IMPRESSAO_DMI_GKME', 'DMI' , cDMI.checked);
      aINI.WriteBool   ('IMPRESSAO_DMI_GKME', 'GLME', cGLME.checked);
      aINI.Free;

      Impressao_GeraisOP_DMI.Release;
      Impressao_GeraisOP_DMI := nil;
end;

procedure TImpressao_GeraisOP_DMI.FormCreate(Sender: TObject);
begin
      if FileExists('fundo_barra.bmp') then Image1.Picture.LoadFromFile('fundo_barra.bmp');
end;

procedure TImpressao_GeraisOP_DMI.FormShow(Sender: TObject);
var
   aINI: TIniFile;
begin
     // Carregando as ultimas opções utilizadas no relatório como default.
     aINI := TIniFile.Create(ExtractFilePath(Application.ExeName)+'ImportaRelatorios.ini');
     cDI.KeyValue  := aINI.ReadString ('IMPRESSAO_DMI_GKME', 'DI'  , '');
     cDMI.checked  := aINI.ReadBool   ('IMPRESSAO_DMI_GKME', 'DMI' , false);
     cGLME.checked := aINI.ReadBool   ('IMPRESSAO_DMI_GKME', 'GLME', false);
     aINI.Free;

     with Dados do begin
          with tDI do begin
               sql.Clear;
               sql.Add('select distinct DI');
               sql.Add('from NotasItens');
               sql.Add('where isnull(DI, '''') <> '''' ');
               sql.Add('order by DI');
               open;
          end;
     end;
end;

procedure TImpressao_GeraisOP_DMI.ppSummaryBand2BeforePrint(Sender: TObject);
begin
     with tEmpresas do begin
          lEndereco.caption := concat(fieldbyname('Representante_Rua').AsString,
                               ', nº', fieldbyname('Representante_Numero').AsString,
                               ', ', fieldbyname('Representante_Complemento').AsString,
                               fieldbyname('Representante_Bairro').AsString);
          lEndereco2.caption := concat(fieldbyname('Representante_Municipio').AsString,
                                       '/', fieldbyname('Representante_Estado').AsString,
                                       ' - ', 'Telefone:', fieldbyname('Representante_Telefone').AsString);
     end;
end;

procedure TImpressao_GeraisOP_DMI.rDMIBeforePrint(Sender: TObject);
begin
      lData.Caption := concat(DataExtenso(tEmpresas.FieldByName('Municipio_Nome').AsString+'('+tEmpresas.FieldByName('Estado').AsString+')', date) );
end;

end.
