object Pedido_DadosVeiculo: TPedido_DadosVeiculo
  Left = 543
  Top = 257
  BorderStyle = bsDialog
  Caption = 'Pedido de Nota Fiscal (Dados do Transporte)'
  ClientHeight = 481
  ClientWidth = 512
  Color = clWindow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 506
    Height = 445
    Align = alClient
    BevelOuter = bvLowered
    Color = clWindow
    DoubleBuffered = True
    ParentDoubleBuffered = False
    TabOrder = 1
    object GroupBox1: TGroupBox
      Left = 18
      Top = 16
      Width = 474
      Height = 100
      Caption = 'Dados do Motorista'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentColor = False
      ParentFont = False
      TabOrder = 0
      object StaticText13: TStaticText
        Left = 10
        Top = 18
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'Nome'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 0
        Transparent = False
        StyleElements = []
      end
      object StaticText4: TStaticText
        Left = 10
        Top = 41
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'CPF'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 2
        Transparent = False
        StyleElements = []
      end
      object DBEdit4: TDBEdit
        Left = 97
        Top = 41
        Width = 126
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Transporte_CPFMotorista'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
      end
      object DBEdit9: TDBEdit
        Left = 97
        Top = 64
        Width = 126
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Transporte_RGMotorista'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 3
      end
      object StaticText8: TStaticText
        Left = 10
        Top = 64
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'RG'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 4
        Transparent = False
        StyleElements = []
      end
      object cNome: TDBComboBox
        Left = 97
        Top = 18
        Width = 363
        Height = 21
        DataField = 'Transporte_NomeMotorista'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 5
        OnExit = cNomeExit
      end
    end
    object GroupBox2: TGroupBox
      Left = 18
      Top = 130
      Width = 474
      Height = 141
      Caption = 'Dados do Ve'#237'culo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentColor = False
      ParentFont = False
      TabOrder = 1
      object StaticText1: TStaticText
        Left = 10
        Top = 18
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'Placa'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 0
        Transparent = False
        StyleElements = []
      end
      object DBEdit1: TDBEdit
        Left = 97
        Top = 18
        Width = 293
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Transporte_Placa'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
      end
      object StaticText2: TStaticText
        Left = 10
        Top = 41
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'C'#243'digo ANTT'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 4
        Transparent = False
        StyleElements = []
      end
      object DBEdit2: TDBEdit
        Left = 97
        Top = 41
        Width = 173
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Transporte_CodigoANTT'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 3
      end
      object StaticText3: TStaticText
        Left = 393
        Top = 18
        Width = 28
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'UF'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 5
        Transparent = False
        StyleElements = []
      end
      object DBEdit3: TDBEdit
        Left = 423
        Top = 18
        Width = 37
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Transporte_PlacaUF'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 2
      end
      object StaticText9: TStaticText
        Left = 10
        Top = 64
        Width = 85
        Height = 60
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'Lacre'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 6
        Transparent = False
        StyleElements = []
      end
      object DBMemo1: TDBMemo
        Left = 97
        Top = 64
        Width = 363
        Height = 60
        DataField = 'Transporte_Lacre'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 7
      end
    end
    object GroupBox3: TGroupBox
      Left = 18
      Top = 289
      Width = 474
      Height = 140
      Caption = 'Dados do Reboque'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'MS Sans Serif'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentColor = False
      ParentFont = False
      TabOrder = 2
      object StaticText5: TStaticText
        Left = 10
        Top = 18
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'Placa'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 0
        Transparent = False
        StyleElements = []
      end
      object DBEdit6: TDBEdit
        Left = 97
        Top = 18
        Width = 293
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Reboque_Placa'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
      end
      object StaticText6: TStaticText
        Left = 10
        Top = 41
        Width = 85
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'C'#243'digo ANTT'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 4
        Transparent = False
        StyleElements = []
      end
      object DBEdit7: TDBEdit
        Left = 97
        Top = 41
        Width = 173
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Reboque_ANTT'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 3
      end
      object StaticText7: TStaticText
        Left = 393
        Top = 18
        Width = 28
        Height = 21
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'UF'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 5
        Transparent = False
        StyleElements = []
      end
      object DBEdit8: TDBEdit
        Left = 423
        Top = 18
        Width = 37
        Height = 21
        CharCase = ecUpperCase
        DataField = 'Reboque_UF'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Pitch = fpFixed
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 2
      end
      object StaticText10: TStaticText
        Left = 10
        Top = 64
        Width = 85
        Height = 60
        AutoSize = False
        BevelInner = bvNone
        BevelKind = bkSoft
        BevelOuter = bvSpace
        BorderStyle = sbsSunken
        Caption = 'Lacre'
        Color = 7293440
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Calibri'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        TabOrder = 6
        Transparent = False
        StyleElements = []
      end
      object DBMemo2: TDBMemo
        Left = 97
        Top = 64
        Width = 363
        Height = 60
        DataField = 'Reboque_Lacre'
        DataSource = Dados.dsPedidos
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 7
      end
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 451
    Width = 512
    Height = 30
    Align = alBottom
    BevelOuter = bvLowered
    Color = clSilver
    TabOrder = 0
    object bSair: TButton
      Left = 450
      Top = 1
      Width = 61
      Height = 28
      Cursor = crHandPoint
      Hint = 'Fecha a janela atual e cancela os processos pendentes.'
      Align = alRight
      Caption = '&OK'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      OnClick = bSairClick
    end
    object bLimpar: TButton
      Left = 386
      Top = 1
      Width = 64
      Height = 28
      Cursor = crHandPoint
      Hint = 'Fecha a janela atual e cancela os processos pendentes.'
      Align = alRight
      Caption = '&Limpar'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      OnClick = bLimparClick
      ExplicitLeft = 380
    end
  end
  object tMotoristas: TMSQuery
    Connection = Dados.Banco_Empresas
    Left = 341
    Top = 120
  end
end
