program Importa;

{$WARN IMPLICIT_STRING_CAST OFF}
{$WARN IMPLICIT_STRING_CAST_LOSS OFF}
{$WARN SUSPICIOUS_TYPECAST OFF}
{$HINTS OFF}

uses
  Forms,
  SysUtils,
  frmDados in 'frmDados.pas' {Dados: TDataModule},
  frmCadastro_Empresas in 'frmCadastro_Empresas.pas' {Cadastro_Empresas},
  FUNCOES in 'FUNCOES.pas',
  frmCadastro_Clientes in 'frmCadastro_Clientes.pas' {Cadastro_Clientes},
  frmCadastro_Fabricantes in 'frmCadastro_Fabricantes.pas' {Cadastro_Fabricantes},
  frmCadastro_NaturezaOperacao in 'frmCadastro_NaturezaOperacao.pas' {Cadastro_NaturezaOperacao},
  frmCadastro_ICMS in 'frmCadastro_ICMS.pas' {Cadastro_ICMS},
  frmCadastro_Moedas in 'frmCadastro_Moedas.pas' {Cadastro_Moedas},
  frmCadastro_Cotacao in 'frmCadastro_Cotacao.pas' {Cadastro_Cotacao},
  frmCadastro_UnidadeMedida in 'frmCadastro_UnidadeMedida.pas' {Cadastro_UnidadeMedida},
  frmCadastro_TipoProduto in 'frmCadastro_TipoProduto.pas' {Cadastro_TipoProduto},
  frmCadastro_Produtos in 'frmCadastro_Produtos.pas' {Cadastro_Produtos},
  frmConfig_TipoNota in 'frmConfig_TipoNota.pas' {Config_TipoNota},
  frmConfig_TipoNotaFormula in 'frmConfig_TipoNotaFormula.pas' {Config_TipoNotaFormula},
  frmCadastro_ImpostosTaxas in 'frmCadastro_ImpostosTaxas.pas' {Cadastro_ImpostosTaxas},
  frmCadastro_NCM in 'frmCadastro_NCM.pas' {Cadastro_NCM},
  frmSobre_Sistema in 'frmSobre_Sistema.pas' {Sobre_Sistema},
  frmCadastro_Bancos in 'frmCadastro_Bancos.pas' {Cadastro_Bancos},
  frmCadastro_TiposDocumentos in 'frmCadastro_TiposDocumentos.pas' {Cadastro_TiposDocumentos},
  frmFinanceiro_Lista in 'frmFinanceiro_Lista.pas' {Financeiro_Lista},
  frmProcesso_Container in 'frmProcesso_Container.pas' {Processo_Container},
  frmProcesso_Adicoes in 'frmProcesso_Adicoes.pas' {Processo_Adicoes},
  frmProcesso_Importacao in 'frmProcesso_Importacao.pas' {Processo_Importacao},
  frmCadastro_CentroCusto in 'frmCadastro_CentroCusto.pas' {Cadastro_CentroCusto},
  frmCadastro_OrgaosPublicos in 'frmCadastro_OrgaosPublicos.pas' {Cadastro_OrgaosPublicos},
  frmPedido in 'frmPedido.pas' {Pedido},
  frmCadastro_Incoterms in 'frmCadastro_Incoterms.pas' {Cadastro_Incoterms},
  frmConfigsis in 'frmConfigsis.pas' {ConfigSis},
  frmSistema_Entrada in 'frmSistema_Entrada.pas' {Sistema_Entrada},
  frmConversor_Moedas in 'frmConversor_Moedas.pas' {Conversor_Moedas},
  frmDMFiscal in 'frmDMFiscal.pas' {dmFiscal: TDataModule},
  frmPedido_NotaRefComplementar in 'frmPedido_NotaRefComplementar.pas' {Pedido_NotaRefComplementar},
  frmPedido_Devolucao in 'frmPedido_Devolucao.pas' {Pedido_Devolucao},
  frmPedido_DevolucaoItens in 'frmPedido_DevolucaoItens.pas' {Pedido_DevolucaoItens},
  frmNotaFiscal_Terceiros in 'frmNotaFiscal_Terceiros.pas' {NotaFiscal_Terceiros},
  frmNotaFiscal_TerceirosItens in 'frmNotaFiscal_TerceirosItens.pas' {NotaFiscal_TerceirosItens},
  frmProcesso_Exportacao in 'frmProcesso_Exportacao.pas' {Processo_Exportacao},
  frmNotaFiscal_TerceirosReferenciaItens in 'frmNotaFiscal_TerceirosReferenciaItens.pas' {NotaFiscal_TerceirosReferenciaItens},
  frmDMContab in 'frmDMContab.pas' {dmContab: TDataModule},
  frmCadastro_PlanoContas in 'frmCadastro_PlanoContas.pas' {Cadastro_PlanoContas},
  frmCadastro_HistoricoPadrao in 'frmCadastro_HistoricoPadrao.pas' {Cadastro_HistoricoPadrao},
  frmCadastro_PlanoContasSaldo in 'frmCadastro_PlanoContasSaldo.pas' {Cadastro_PlanoContasSaldo},
  frmContabilidade_Lancamentos in 'frmContabilidade_Lancamentos.pas' {Contabilidade_Lancamentos},
  frmContabilidade_LancamentosPesquisar in 'frmContabilidade_LancamentosPesquisar.pas' {Contabilidade_LancamentosPesquisar},
  frmSplash_Screen in 'frmSplash_Screen.pas' {Splash_Screen},
  frmPedido_Itens in 'frmPedido_Itens.pas' {Pedido_Itens},
  frmPedido_ItensCompraInterna in 'frmPedido_ItensCompraInterna.pas' {Pedido_ItensCompraInterna},
  frmCadastro_ClassificacaoFinanceira in 'frmCadastro_ClassificacaoFinanceira.pas' {Cadastro_ClassificacaoFinanceira},
  frmNotaFiscal_Servico in 'frmNotaFiscal_Servico.pas' {NotaFiscal_Servico},
  frmCadastro_Servicos in 'frmCadastro_Servicos.pas' {Cadastro_Servicos},
  frmConfig_LayoutMemorando in 'frmConfig_LayoutMemorando.pas' {Config_LayoutMemorando},
  frmConfig_LayoutMemorandoInformar in 'frmConfig_LayoutMemorandoInformar.pas' {Config_LayoutMemorandoInformar},
  frmImpressao_ExportacaoMemorandoOP in 'frmImpressao_ExportacaoMemorandoOP.pas' {Impressao_ExportacaoMemorandoOP},
  frmMemorando_Visualizar in 'frmMemorando_Visualizar.pas' {Memorando_Visualizar},
  frmPedido_Servico in 'frmPedido_Servico.pas' {Pedido_Servico},
  frmImpressao_NotaFiscalServico in 'frmImpressao_NotaFiscalServico.pas' {Impressao_NotaFiscalServico},
  frmConfig_LayoutNotaServico in 'frmConfig_LayoutNotaServico.pas' {Config_LayoutNotaServico},
  frmConfig_LayoutNotaServicoInformar in 'frmConfig_LayoutNotaServicoInformar.pas' {Config_LayoutNotaServicoInformar},
  frmUtilitario_ExportaTexto in 'frmUtilitario_ExportaTexto.pas' {Utilitario_ExportaTexto},
  frmUtilitarios_ExportaSINTEGRA in 'frmUtilitarios_ExportaSINTEGRA.pas' {Utilitarios_ExportaSintegra},
  frmJanela_Processamento in 'frmJanela_Processamento.pas' {Janela_Processamento},
  frmImpressao_Visualizar in 'frmImpressao_Visualizar.pas' {Impressao_Visualizar},
  frmImpressao_FiscaisOP_LivroSaida in 'frmImpressao_FiscaisOP_LivroSaida.pas' {Impressao_FiscaisOP_LivroSaida},
  frmImpressao_FiscaisOP_LivroEntrada in 'frmImpressao_FiscaisOP_LivroEntrada.pas' {Impressao_FiscaisOP_LivroEntrada},
  frmImpressao_FiscaisOP_RCPE_P3 in 'frmImpressao_FiscaisOP_RCPE_P3.pas' {Impressao_FiscaisOP_RCPE_P3},
  frmImpressao_FiscaisOP_Inventario_P72 in 'frmImpressao_FiscaisOP_Inventario_P72.pas' {Impressao_FiscaisOP_Inventario_P72},
  frmImpressao_FiscaisOP_RAICMS_P9 in 'frmImpressao_FiscaisOP_RAICMS_P9.pas' {Impressao_FiscaisOP_RAICMS_P9},
  frmImpressao_FiscaisOP_RAIPI_P9 in 'frmImpressao_FiscaisOP_RAIPI_P9.pas' {Impressao_FiscaisOP_RAIPI_P9},
  frmImpressao_FiscaisOP_LivroServicoPrestados in 'frmImpressao_FiscaisOP_LivroServicoPrestados.pas' {Impressao_FiscaisOP_LivroServicoPrestados},
  frmCadastro_Municipios in 'frmCadastro_Municipios.pas' {Cadastro_Municipios},
  frmNotaFiscal_OutrosValoresIPI in 'frmNotaFiscal_OutrosValoresIPI.pas' {NotaFiscal_OutrosValoresIPI},
  frmUtilitarios_ExportaSPED_Fiscal in 'frmUtilitarios_ExportaSPED_Fiscal.pas' {Utilitarios_ExportaSPED_Fiscal},
  frmImpressao_Fiscais_ApuracaoPISCOFINS in 'frmImpressao_Fiscais_ApuracaoPISCOFINS.pas' {Impressao_Fiscais_ApuracaoPISCOFINS},
  frmImpressao_ContabeisOP_PlanoContas in 'frmImpressao_ContabeisOP_PlanoContas.pas' {Impressao_ContabeisOP_PlanoContas},
  frmImpressao_ContabeisOP_Critica in 'frmImpressao_ContabeisOP_Critica.pas' {Impressao_ContabeisOP_Critica},
  frmImpressao_ContabeisOP_Historicos in 'frmImpressao_ContabeisOP_Historicos.pas' {Impressao_ContabeisOP_Historicos},
  frmImpressao_ContabeisOP_Razao in 'frmImpressao_ContabeisOP_Razao.pas' {bSelecionar},
  frmImpressao_ContabeisOP_Balancete in 'frmImpressao_ContabeisOP_Balancete.pas' {Impressao_ContabeisOP_Balancete},
  frmImpressao_ContabeisOP_Diario in 'frmImpressao_ContabeisOP_Diario.pas' {Impressao_ContabeisOP_Diario},
  frmImpressao_ContabeisSelecao_Razao in 'frmImpressao_ContabeisSelecao_Razao.pas' {Impressao_ContabeisSelecao_Razao},
  frmImpressao_FiscaisOP_CIAP in 'frmImpressao_FiscaisOP_CIAP.pas' {Impressao_FiscaisOP_CIAP},
  frmNotaFiscal_EstornoDebitos in 'frmNotaFiscal_EstornoDebitos.pas' {NotaFiscal_EstornoDebitos},
  frmSistema_LOG in 'frmSistema_LOG.pas' {Sistema_LOG},
  frmImpressao_Financeiros_Duplicatas in 'frmImpressao_Financeiros_Duplicatas.pas' {Impressao_Financeiros_Duplicatas},
  frmMenu_Principal in 'frmMenu_Principal.pas' {Menu_Principal},
  frmFinanceiro_Duplicatas in 'frmFinanceiro_Duplicatas.pas' {Financeiro_Duplicatas},
  frmJanela_Comunicacao in 'frmJanela_Comunicacao.pas' {Janela_Comunicacao},
  frmNfe_Inutilizacao in 'frmNfe_Inutilizacao.pas' {NFe_Inutilizacao},
  frmImpressao_DANFE in 'frmImpressao_DANFE.pas' {Impressao_DANFE},
  frmModalidadePgto_PedidoParcelas in 'frmModalidadePgto_PedidoParcelas.pas' {ModalidadePgto_PedidoParcelas},
  frmCadastro_Paises in 'frmCadastro_Paises.pas' {Cadastro_Paises},
  frmNFe_CartaCorrecao in 'frmNFe_CartaCorrecao.pas' {NFe_CartaCorrecao},
  frmJanela_BACKUP in 'frmJanela_BACKUP.pas' {Janela_BACKUP},
  frmNotaFiscal_VisualizarPedido in 'frmNotaFiscal_VisualizarPedido.pas' {NotaFiscal_VisualizarPedido},
  frmFinanceiro_LancamentoDadosBancarios in 'frmFinanceiro_LancamentoDadosBancarios.pas' {Financeiro_LancamentoDadosBancarios},
  frmFinanceiro_LancamentoParcelas in 'frmFinanceiro_LancamentoParcelas.pas' {Financeiro_LancamentoParcelas},
  frmCadastro_TiposComissao in 'frmCadastro_TiposComissao.pas' {Cadastro_TiposComissao},
  frmModalidadePgto_Parcelas in 'frmModalidadePgto_Parcelas.pas' {ModalidadePgto_Parcelas},
  frmImpressao_NotaFiscalServicoReimpressao in 'frmImpressao_NotaFiscalServicoReimpressao.pas' {Impressao_NotaFiscalServicoReimpressao},
  frmNotaServico_Cancelar in 'frmNotaServico_Cancelar.pas' {NotaServico_Cancelar},
  frmJanela_ProcessamentoSPED in 'frmJanela_ProcessamentoSPED.pas' {Janela_ProcessamentoSPED},
  frmCadastro_ConsultaCST in 'frmCadastro_ConsultaCST.pas' {Cadastro_ConsultaCST},
  frmImpressao_FinanceiroOP_PrestacaoProcesso in 'frmImpressao_FinanceiroOP_PrestacaoProcesso.pas' {Impressao_FinanceirosOP_PrestacaoProcesso},
  frmModificarNF in 'frmModificarNF.pas' {ModificarNF},
  frmImpressao_ProcessosOP_Estoque in 'frmImpressao_ProcessosOP_Estoque.pas' {Impressao_ProcessosOP_Estoque},
  frmImpressao_GeraisOP_DeclaracaoNF in 'frmImpressao_GeraisOP_DeclaracaoNF.pas' {Impressao_GeraisOP_DeclaracaoNF},
  frmUtilitario_ExportaTextoCampos in 'frmUtilitario_ExportaTextoCampos.pas' {Utilitario_ExportaTextoCampos},
  frmUtilitario_ExportaTextoCamposItem in 'frmUtilitario_ExportaTextoCamposItem.pas' {Utilitario_ExportaTextoCamposItem},
  frmPedido_DadosVeiculo in 'frmPedido_DadosVeiculo.pas' {Pedido_DadosVeiculo},
  frmImpressao_FiscaisOP_NCM in 'frmImpressao_FiscaisOP_NCM.pas' {Impressao_FiscaisOP_NCM},
  frmImpressao_ProcessosOP_Fechamento in 'frmImpressao_ProcessosOP_Fechamento.pas' {Impressao_ProcessosOP_Fechamento},
  frmImpressao_Faturamento_OP_NotasEmitidas in 'frmImpressao_Faturamento_OP_NotasEmitidas.pas' {Impressao_Faturamento_OP_NotasEmitidas},
  frmFinanceiro_BaixaLote in 'frmFinanceiro_BaixaLote.pas' {Financeiro_BaixaLote},
  frmFinanceiro_BaixaLoteDados in 'frmFinanceiro_BaixaLoteDados.pas' {Financeiro_BaixaLoteDados},
  frmFinanceiro_TransferenciaBancaria in 'frmFinanceiro_TransferenciaBancaria.pas' {Financeiro_TransferenciaBancaria},
  frmFinanceiro_SPCheque in 'frmFinanceiro_SPCheque.pas' {Financeiro_SPCheque},
  frmFinanceiro_TransferenciaProcesso in 'frmFinanceiro_TransferenciaProcesso.pas' {Financeiro_TransferenciaProcesso},
  frmImpressao_Cadastros_ClassificacaoFinanceira in 'frmImpressao_Cadastros_ClassificacaoFinanceira.pas' {Impressao_Cadastros_ClassificacaoFinanceira},
  frmPedido_Outros in 'frmPedido_Outros.pas' {Pedido_Outros},
  frmPedido_ItensOutros in 'frmPedido_ItensOutros.pas' {Pedido_ItensOutros},
  frmImpressao_Faturamento_DetalhamentoItens in 'frmImpressao_Faturamento_DetalhamentoItens.pas' {Impressao_Faturamento_DetalhamentoItens},
  frmFinanceiro_EstornoBaixa in 'frmFinanceiro_EstornoBaixa.pas' {Financeiro_EstornoBaixa},
  frmFinanceiro_BaixaCheque in 'frmFinanceiro_BaixaCheque.pas' {Financeiro_BaixaCheque},
  frmPedido_TaxaLucro in 'frmPedido_TaxaLucro.pas' {Pedido_TaxaLucro},
  frmImpressao_FiscaisOP_CFOP in 'frmImpressao_FiscaisOP_CFOP.pas' {Impressao_FiscaisOP_CFOP},
  frmImpressao_Cadastros_Clientes in 'frmImpressao_Cadastros_Clientes.pas' {Impressao_Cadastros_Clientes},
  frmPedido_ItensQuantidade in 'frmPedido_ItensQuantidade.pas' {Pedido_ItensQuantidade},
  frmPedido_ItensQuantidade_CInterna in 'frmPedido_ItensQuantidade_CInterna.pas' {Pedido_ItensQuantidade_CInterna},
  frmImpressao_FinanceirosOP_ComissaoTrader in 'frmImpressao_FinanceirosOP_ComissaoTrader.pas' {Impressao_FinanceirosOP_ComissaoTrader},
  frmImpressao_Cadastros_Fornecedores in 'frmImpressao_Cadastros_Fornecedores.pas' {Impressao_Cadastros_Fornecedores},
  frmProcesso_Historico in 'frmProcesso_Historico.pas' {Processo_Historico},
  frmProcesso_SimulacaoCalculo in 'frmProcesso_SimulacaoCalculo.pas' {Processo_SimulacaoCalculo},
  frmImpressao_FinanceirosOP_ConcAdiant2 in 'frmImpressao_FinanceirosOP_ConcAdiant2.pas' {Impressao_FinanceirosOP_ConcAdiant2},
  frmProposta_ExportacaoImpDesp in 'frmProposta_ExportacaoImpDesp.pas' {Proposta_ExportacaoImpDesp},
  frmImpressao_Cadastros_Produtos in 'frmImpressao_Cadastros_Produtos.pas' {Impressao_Cadastros_Produtos},
  frmCadastro_BeneficiosFiscais in 'frmCadastro_BeneficiosFiscais.pas' {Cadastro_BeneficiosFiscais},
  frmPedido_ItensOutrosValorRateio in 'frmPedido_ItensOutrosValorRateio.pas' {Pedido_ItensOutrosValorRateio},
  frmFinanceiro_ConciliacaoBancaria in 'frmFinanceiro_ConciliacaoBancaria.pas' {Financeiro_ConciliacaoBancaria},
  frmCadastro_BancosHistoricos in 'frmCadastro_BancosHistoricos.pas' {Cadastro_BancosHistoricos},
  frmImpressao_FinanceirosOP_Cambio in 'frmImpressao_FinanceirosOP_Cambio.pas' {Impressao_FinanceirosOP_Cambio},
  frmUtilitarios_ExportaDNF in 'frmUtilitarios_ExportaDNF.pas' {Utilitarios_ExportaDNF},
  frmFinanceiro_RelacaoContratos in 'frmFinanceiro_RelacaoContratos.pas' {Financeiro_RelacaoContratos},
  frmImpressao_FinanceirosOP_FaturamentoMensal in 'frmImpressao_FinanceirosOP_FaturamentoMensal.pas' {Impressao_FinanceirosOP_FaturamentoMensal},
  frmImpressao_FinanceirosSN in 'frmImpressao_FinanceirosSN.pas' {Impressao_FinanceirosSN},
  frmCadastro_ProdutosSeriais in 'frmCadastro_ProdutosSeriais.pas' {Cadastro_ProdutosSeriais},
  frmCadastro_DREGrupos in 'frmCadastro_DREGrupos.pas' {Cadastro_DREGrupos},
  frmCadastro_TiposProcesso in 'frmCadastro_TiposProcesso.pas' {Cadastro_TiposProcesso},
  frmCadastro_RamoAtividade in 'frmCadastro_RamoAtividade.pas' {Cadastro_RamoAtividade},
  frmUtilitarios_ExportaSPED_PISCOFINS in 'frmUtilitarios_ExportaSPED_PISCOFINS.pas' {Utilitarios_ExportaSPED_PISCOFINS},
  frmFinanceiro_Duplicar in 'frmFinanceiro_Duplicar.pas' {Financeiro_Duplicar},
  frmImpressao_ProcessosOP_Relacao in 'frmImpressao_ProcessosOP_Relacao.pas' {Impressao_ProcessosOP_Relacao},
  frmNFe_RecuperarXML in 'frmNFe_RecuperarXML.pas' {NFe_RecuperarXML},
  frmImpressao_ProcessosOP_Acompanhamento in 'frmImpressao_ProcessosOP_Acompanhamento.pas' {Impressao_ProcessosOP_Acompanhamento},
  frmUtilitario_ImportarTexto in 'frmUtilitario_ImportarTexto.pas' {Utilitario_ImportarTexto},
  frmImpressao_GeraisOP_Recibo in 'frmImpressao_GeraisOP_Recibo.pas' {ImpressaoGeraisOP_Recibo},
  frmNotaFiscal_Eletronica2G in 'frmNotaFiscal_Eletronica2G.pas' {NotaFiscal_Eletronica2G},
  frmImpressao_Financeiros_CopiaCheque in 'frmImpressao_Financeiros_CopiaCheque.pas' {Impressao_Financeiros_CopiaCheque},
  frmFinanceiro_SolicitacaoPagamentos in 'frmFinanceiro_SolicitacaoPagamentos.pas' {Financeiro_SolicitacaoPagamentos},
  frmFinanceiro_SolicitacaoNumerario in 'frmFinanceiro_SolicitacaoNumerario.pas' {Financeiro_SolicitacaoNumerario},
  frmFinanceiro_SolicitacaoItens in 'frmFinanceiro_SolicitacaoItens.pas' {Financeiro_SolicitacaoItens},
  frmFinanceiro_SolicitacaoProcesso in 'frmFinanceiro_SolicitacaoProcesso.pas' {Financeiro_SolicitacaoProcesso},
  frmFinanceiro_SolicitacaoItensDeleta in 'frmFinanceiro_SolicitacaoItensDeleta.pas' {Financeiro_SolicitacaoItensDeleta},
  frmUtilitarios_Importar_NFe_Propria in 'frmUtilitarios_Importar_NFe_Propria.pas' {Utilitarios_Importar_NFe_Propria},
  frmUtilitarios_ImportaEXCEL in 'frmUtilitarios_ImportaEXCEL.pas' {Utilitarios_ImportaEXCEL},
  frmFinanceiro_BloquearPeriodo in 'frmFinanceiro_BloquearPeriodo.pas' {Financeiro_BloquearPeriodo},
  frmDMComercial in 'frmDMComercial.pas' {dmComercial: TDataModule},
  frmCadastro_TabelaComissoes in 'frmCadastro_TabelaComissoes.pas' {Cadastro_TabelaComissoes},
  frmUtilitarios_Restore in 'frmUtilitarios_Restore.pas' {Utilitarios_Restore},
  frmUtilitario_ImportarEmpresa in 'frmUtilitario_ImportarEmpresa.pas' {Utilitario_ImportarEmpresa},
  frmDMImporta in 'frmDMImporta.pas' {dmImporta: TDataModule},
  frmCadastro_ClassificacaoNivel in 'frmCadastro_ClassificacaoNivel.pas' {Cadastro_ClassificacaoNivel},
  frmImpressao_FinanceirosOP_ComissoesPagar in 'frmImpressao_FinanceirosOP_ComissoesPagar.pas' {Impressao_FinanceirosOP_ComissoesPagar},
  frmCadastro_ProdutosLinhas in 'frmCadastro_ProdutosLinhas.pas' {Cadastro_ProdutosLinhas},
  frmImpressao_Faturamento_MediaVenda in 'frmImpressao_Faturamento_MediaVenda.pas' {Impressao_Faturamento_MediaVenda},
  frmCadastro_Recursos in 'frmCadastro_Recursos.pas' {Cadastro_Recursos},
  frmProcesso_Fechamento in 'frmProcesso_Fechamento.pas' {Processo_Fechamento},
  frmProcesso_FechamentoItensFiltro in 'frmProcesso_FechamentoItensFiltro.pas' {Processo_FechamentoItensFiltro},
  frmPedido_ItensOutrosSeriais in 'frmPedido_ItensOutrosSeriais.pas' {Pedido_ItensSeriais},
  frmImpressao_FinanceirosOP_VendasRepresentantes in 'frmImpressao_FinanceirosOP_VendasRepresentantes.pas' {Impressao_FinanceirosOP_VendasRepresentantes},
  frmImpressao_ProcessosOP_Dados in 'frmImpressao_ProcessosOP_Dados.pas' {Impressao_ProcessosOP_Dados},
  frmImpressao_ProcessosOP_ccCliente in 'frmImpressao_ProcessosOP_ccCliente.pas' {Impressao_ProcessosOP_ccCliente},
  frmImpressao_ProcessosOP_Prazo in 'frmImpressao_ProcessosOP_Prazo.pas' {Impressao_ProcessosOP_Prazo},
  frmImpressao_FinanceirosOP_RecDesp in 'frmImpressao_FinanceirosOP_RecDesp.pas' {Impressao_Financeiros_RecDesp},
  frmProcesso_InvoiceQuantidade in 'frmProcesso_InvoiceQuantidade.pas' {Processo_InvoiceQuantidade},
  frmImpressao_ProcessosOP_Rentabilidade in 'frmImpressao_ProcessosOP_Rentabilidade.pas' {Impressao_ProcessosOP_Rentabilidade},
  frmImpressao_ProcessosOP_DemoTX in 'frmImpressao_ProcessosOP_DemoTX.pas' {Impressao_ProcessosOP_DemoTX},
  frmImpressao_ProcessosOP_ContratoCambio in 'frmImpressao_ProcessosOP_ContratoCambio.pas' {Impressao_ProcessosOP_ContratoCambio},
  frmCadastro_LocaisDesembaraco in 'frmCadastro_LocaisDesembaraco.pas' {Cadastro_LocaisDesembaraco},
  frmImpressao_Faturamento_OP_Previsao in 'frmImpressao_Faturamento_OP_Previsao.pas' {Impressao_Faturamento_OP_Previsao},
  frmCIAP in 'frmCIAP.pas' {CIAP},
  frmProcesso_Desativar in 'frmProcesso_Desativar.pas' {Processo_Desativar},
  frmImpressao_ProcessosOP_InvoiceImp in 'frmImpressao_ProcessosOP_InvoiceImp.pas' {Impressao_ProcessosOP_InvoiceImp},
  frmFinanceiro_Pesquisa in 'frmFinanceiro_Pesquisa.pas' {Financeiro_Pesquisa},
  frmImpressao_FinanceirosOP_Recebiveis in 'frmImpressao_FinanceirosOP_Recebiveis.pas' {Impressao_FinanceirosOP_Recebiveis},
  frmImpressao_Faturamento_Vendas in 'frmImpressao_Faturamento_Vendas.pas' {Impressao_Faturamento_Vendas},
  frmImpressao_Faturamento_Pedidos in 'frmImpressao_Faturamento_Pedidos.pas' {Impressao_Faturamento_Pedidos},
  frmImpressao_Cadastros_TipoNota in 'frmImpressao_Cadastros_TipoNota.pas' {Impressao_Cadastros_TipoNota},
  frmCadastro_ModalidadesPagamento in 'frmCadastro_ModalidadesPagamento.pas' {Cadastro_ModalidadesPagamento},
  frmCadastro_CondicaoCambial in 'frmCadastro_CondicaoCambial.pas' {Cadastro_CondicaoCambial},
  frmUtilitarios_Importar_NFe_TerceirosProv in 'frmUtilitarios_Importar_NFe_TerceirosProv.pas' {Utilitarios_Importar_NFe_TerceirosProv},
  frmImpressao_Faturamento_OP_NotasSemDestaqueICMS in 'frmImpressao_Faturamento_OP_NotasSemDestaqueICMS.pas' {Impressao_Faturamento_OP_NotasSemDestaqueICMS},
  frmImpressao_ProcessosOP_ControleInvoice in 'frmImpressao_ProcessosOP_ControleInvoice.pas' {Impressao_ProcessosOP_ControleInvoice},
  frmFiscal_AberturaEstoque in 'frmFiscal_AberturaEstoque.pas' {Fiscal_AberturaEstoque},
  frmImpressao_ProdutosVendidos in 'frmImpressao_ProdutosVendidos.pas' {Impressao_ProdutosVendidos},
  frmImpressao_ProcessosOP_Container in 'frmImpressao_ProcessosOP_Container.pas' {Impressao_ProcessosOP_Container},
  frmImpressao_Faturamento_OP_Estoque in 'frmImpressao_Faturamento_OP_Estoque.pas' {Impressao_Faturamento_OP_Estoque},
  frmProcesso_ContratoCambio2 in 'frmProcesso_ContratoCambio2.pas' {Processo_ContratoCambio2},
  frmProcesso_ContratoCambioItem in 'frmProcesso_ContratoCambioItem.pas' {Processo_ContratoCambioItem},
  frmUtilitario_SistemaAcoes in 'frmUtilitario_SistemaAcoes.pas' {Utilitario_SistemaAcoes},
  frmUtilitarios_Importar_NFe_Terceiros in 'frmUtilitarios_Importar_NFe_Terceiros.pas' {Utilitarios_Importar_NFe_Terceiros},
  frmImpressao_Faturamento_RanckingCliente in 'frmImpressao_Faturamento_RanckingCliente.pas' {Impressao_Faturamento_RanckingCliente},
  frmNFe_CancelamentoAdministrativo in 'frmNFe_CancelamentoAdministrativo.pas' {NFe_CancelamentoAdministrativo},
  frmConfig_TipoNotaTerceiros in 'frmConfig_TipoNotaTerceiros.pas' {Config_TipoNotaTerceiros},
  frmImpressao_FinanceirosOP_JurosMulta in 'frmImpressao_FinanceirosOP_JurosMulta.pas' {Impressao_FinanceirosOP_JurosMulta},
  frmImpressao_FaturamentoOP_EstoqueResumido in 'frmImpressao_FaturamentoOP_EstoqueResumido.pas' {Impressao_FaturamentoOP_EstoqueResumido},
  frmImpressao_FinanceirosOP_DRE in 'frmImpressao_FinanceirosOP_DRE.pas' {Impressao_FinanceirosOP_DRE},
  frmImpressao_GeraisOP_CartaCorrecao in 'frmImpressao_GeraisOP_CartaCorrecao.pas' {Impressao_GeraisOP_CartaCorrecao},
  frmImpressao_FaturamentoOP_DesdobDupl in 'frmImpressao_FaturamentoOP_DesdobDupl.pas' {Impressao_FaturamentoOP_DesdobDupl},
  frmSistema_TrocarEmpresa in 'frmSistema_TrocarEmpresa.pas' {Sistema_TrocarEmpresa},
  frmUtilitarios_ExportaSPED_ECF in 'frmUtilitarios_ExportaSPED_ECF.pas' {Utilitarios_ExportaSPED_ECF},
  frmChecagem in 'frmChecagem.pas' {Checagem},
  frmImpressao_Faturamento_DetalhamentoPISCOFINS in 'frmImpressao_Faturamento_DetalhamentoPISCOFINS.pas' {Impressao_Faturamento_DetalhamentoPISCOFINS},
  frmContabilidade_Edicao in 'frmContabilidade_Edicao.pas' {Contabilidade_Edicao},
  frmNFe_Cancelamento in 'frmNFe_Cancelamento.pas' {NFe_Cancelamento},
  frmUtilitarios_ExportaADECOFIS in 'frmUtilitarios_ExportaADECOFIS.pas' {Utilitarios_ExportaADECOFIS},
  frmImpressao_Faturamento_OP_NotasEmitidasServ in 'frmImpressao_Faturamento_OP_NotasEmitidasServ.pas' {Impressao_Faturamento_OP_NotasEmitidasServ},
  frmImpressao_FinanceirosOP_VendasRepresProdutos in 'frmImpressao_FinanceirosOP_VendasRepresProdutos.pas' {Impressao_FinanceirosOP_VendasRepresProdutos},
  frmFinanceiro_TransferenciaClassificacao in 'frmFinanceiro_TransferenciaClassificacao.pas' {Financeiro_TransferenciaClassificacao},
  frmNFe_CartaCorrecaoItem in 'frmNFe_CartaCorrecaoItem.pas' {NFe_CartaCorrecaoItem},
  frmNFe_CartaCorrecaoItemQuantidade in 'frmNFe_CartaCorrecaoItemQuantidade.pas' {NFe_CartaCorrecaoItemQuantidade},
  frmProcesso_GLME in 'frmProcesso_GLME.pas' {Processo_GLME},
  frmImpressao_Faturamento_MediaBCR in 'frmImpressao_Faturamento_MediaBCR.pas' {Impressao_Faturamento_MediaBCR},
  frmPedido_DevolucaoItensTerceiros in 'frmPedido_DevolucaoItensTerceiros.pas' {Pedido_DevolucaoItensTerceiros},
  frmMinuta in 'frmMinuta.pas' {Minuta},
  frmImpressao_ExportacaoReMemorando in 'frmImpressao_ExportacaoReMemorando.pas' {Impressao_ExportacaoReMemorando},
  frmImpressao_ProdutosRanking in 'frmImpressao_ProdutosRanking.pas' {Impressao_ProdutosRanking},
  frmUtilitarios_AjustarEstoqueInventario in 'frmUtilitarios_AjustarEstoqueInventario.pas' {Utilitarios_AjustarEstoqueInventario},
  frmImpressao_ProdutosHistorico in 'frmImpressao_ProdutosHistorico.pas' {Impressao_ProdutosHistorico},
  frmFiscal_TransferenciaEstoque in 'frmFiscal_TransferenciaEstoque.pas' {Fiscal_TransferenciaEstoque},
  frmCadastro_Fornecedores in 'frmCadastro_Fornecedores.pas' {Cadastro_Fornecedores},
  frmNotaFiscal_TerceirosEfetivar in 'frmNotaFiscal_TerceirosEfetivar.pas' {NotaFiscal_TerceirosEfetivar},
  frmUtilitarios_EnviarDados in 'frmUtilitarios_EnviarDados.pas' {Utilitarios_EnviarDados},
  frmCadastro_ProdutosDetalhes in 'frmCadastro_ProdutosDetalhes.pas' {Cadastro_ProdutosDetalhes},
  frmCadastro_Detalhes in 'frmCadastro_Detalhes.pas' {Cadastro_Detalhes},
  frmNotaFiscal_TerceirosItensDetalhe in 'frmNotaFiscal_TerceirosItensDetalhe.pas' {NotaFiscal_TerceirosItensDetalhe},
  frmImpressao_Faturamento_ComposicaoProc in 'frmImpressao_Faturamento_ComposicaoProc.pas' {Impressao_Faturamento_ComposicaoProc},
  frmFinanceiro_EmprestimosCG in 'frmFinanceiro_EmprestimosCG.pas' {Financeiro_EmprestimosCG},
  frmFinanceiro_EmprestimosDD in 'frmFinanceiro_EmprestimosDD.pas' {Financeiro_EmprestimosDD},
  frmAtualiza_Sistema in 'frmAtualiza_Sistema.pas' {Atualiza_Sistema},
  frmUtilitarios_Importar_CTe_Terceiros in 'frmUtilitarios_Importar_CTe_Terceiros.pas' {Utilitarios_Importar_CTe_Terceiros},
  frmImpressao_FinanceirosOP_EmprestimoDD in 'frmImpressao_FinanceirosOP_EmprestimoDD.pas' {Impressao_FinanceirosOP_EmprestimoDD},
  frmPedido_OutrosDuplicar in 'frmPedido_OutrosDuplicar.pas' {Pedido_OutrosDuplicar},
  frmImpressao_GeraisOP_EtiquetaVolumes in 'frmImpressao_GeraisOP_EtiquetaVolumes.pas' {Impressao_GeraisOP_EtiquetaVolumes},
  frmEstoque_Minimo in 'frmEstoque_Minimo.pas' {Estoque_Minimo},
  frmCadastro_FornecedoresFiliais in 'frmCadastro_FornecedoresFiliais.pas' {Cadastro_FornecedoresFiliais},
  frmConfig_TipoNotaFiliais in 'frmConfig_TipoNotaFiliais.pas' {Config_TipoNotaFiliais},
  frmPedido_CTE in 'frmPedido_CTE.pas' {Pedido_CTE},
  frmCadastro_Destinatarios in 'frmCadastro_Destinatarios.pas' {Cadastro_Destinatarios},
  frmCadastro_Expedidor in 'frmCadastro_Expedidor.pas' {Cadastro_Expedidor},
  frmCadastro_Recebedor in 'frmCadastro_Recebedor.pas' {Cadastro_Recebedor},
  frmImpressao_FinanceirosOP_Endividamento in 'frmImpressao_FinanceirosOP_Endividamento.pas' {Impressao_FinanceirosOP_Endividamento},
  frmCadastro_AjustarPrecos in 'frmCadastro_AjustarPrecos.pas' {Cadastro_AjustarPrecos},
  frmFinanceiro_EmprestimosFN in 'frmFinanceiro_EmprestimosFN.pas' {Financeiro_EmprestimosFN},
  frmFinanceiro_EmprestimosFNItem in 'frmFinanceiro_EmprestimosFNItem.pas' {Financeiro_EmprestimosFNItem},
  frmFinanceiro_EmprestimosFNLiquidar in 'frmFinanceiro_EmprestimosFNLiquidar.pas' {Financeiro_EmprestimosFNLiquidar},
  frmFinanceiro_BoletosGerar in 'frmFinanceiro_BoletosGerar.pas' {Financeiro_BoletosGerar},
  frmFinanceiro_BoletoLote in 'frmFinanceiro_BoletoLote.pas' {Financeiro_BoletoLote},
  frmImpressao_FinanceirosOP_EmprestimoCG in 'frmImpressao_FinanceirosOP_EmprestimoCG.pas' {Impressao_FinanceirosOP_EmprestimoCG},
  frmImpressao_Financeiros_FluxoCaixa in 'frmImpressao_Financeiros_FluxoCaixa.pas' {Impressao_Financeiros_FluxoCaixa},
  frmImpressao_FinanceirosOP_EmprestimoFINIMP in 'frmImpressao_FinanceirosOP_EmprestimoFINIMP.pas' {Impressao_FinanceirosOP_EmprestimoFINIMP},
  frmProcesso_AdicoesOrdem in 'frmProcesso_AdicoesOrdem.pas' {Processo_AdicoesOrdem},
  frmFinanceiro_Lancamento in 'frmFinanceiro_Lancamento.pas' {Financeiro_Lancamento},
  frmImpressao_Financeiros_FluxoCaixaDetalhado in 'frmImpressao_Financeiros_FluxoCaixaDetalhado.pas' {Impressao_Financeiros_FluxoCaixaDetalhado},
  frmImpressao_Processos_PrevisaoDespesas in 'frmImpressao_Processos_PrevisaoDespesas.pas' {Impressao_Processos_PrevisaoDespesas},
  frmFinanceiro_PedidosRepresentantesExcel in 'frmFinanceiro_PedidosRepresentantesExcel.pas' {Financeiro_PedidosRepresentantesExcel},
  frmFinanceiro_RecebimentosClientes in 'frmFinanceiro_RecebimentosClientes.pas' {Financeiro_RecebimentosClientes},
  frmUtilitarios_ExportaRemessaDuplicatas in 'frmUtilitarios_ExportaRemessaDuplicatas.pas' {Utilitarios_ExportaRemessaDuplicatas},
  frmPedido_Excluir in 'frmPedido_Excluir.pas' {Pedido_Excluir},
  frmNFE_ManifestacaoDestinatario in 'frmNFE_ManifestacaoDestinatario.pas' {NFE_ManifestacaoDestinatario},
  frmPedido_Televendas in 'frmPedido_Televendas.pas' {Pedido_Televendas},
  frmPedido_TelevendasItens in 'frmPedido_TelevendasItens.pas' {Pedido_TelevendasItens},
  frmUtilitarios_ExportaRemessaBoletos in 'frmUtilitarios_ExportaRemessaBoletos.pas' {Utilitarios_ExportaRemessaBoletos},
  frmCadastro_Alugueis2 in 'frmCadastro_Alugueis2.pas' {Cadastro_Alugueis2},
  frmCadastros_UsuariosPerfil in 'frmCadastros_UsuariosPerfil.pas' {Cadastros_UsuariosPerfil},
  frmImpressao_Faturamento_RelacaoPedVendas in 'frmImpressao_Faturamento_RelacaoPedVendas.pas' {Impressao_Faturamento_RelacaoPedVendas},
  frmImpressao_FinanceirosOP_DREGerencial in 'frmImpressao_FinanceirosOP_DREGerencial.pas' {Impressao_FinanceirosOP_DREGerencial},
  frmUtilitarios_ImportaRemessaBoletos in 'frmUtilitarios_ImportaRemessaBoletos.pas' {Utilitarios_ImportaRemessaBoletos},
  frmJanela_Email in 'frmJanela_Email.pas' {Janela_Email},
  frmImpressao_Estoque_Inventario in 'frmImpressao_Estoque_Inventario.pas' {Impressao_Estoque_Inventario},
  frmLogistica_ConsultaProdutos in 'frmLogistica_ConsultaProdutos.pas' {Logistica_ConsultaProdutos},
  frmUtilitarios_ImportarPlanoContas in 'frmUtilitarios_ImportarPlanoContas.pas' {Utilitarios_ImportarPlanoContas},
  frmImpressao_FiscaisOP_Inventario_Novo in 'frmImpressao_FiscaisOP_Inventario_Novo.pas' {Impressao_FiscaisOP_Inventario_Novo},
  frmPedido_ItensOutrosQuantidade in 'frmPedido_ItensOutrosQuantidade.pas' {Pedido_ItensOutrosQuantidade},
  frmUtilitarios_ImportarDadosDI in 'frmUtilitarios_ImportarDadosDI.pas' {Utilitarios_ImportarDadosDI},
  frmImpressao_Estoque_FichaEstoque in 'frmImpressao_Estoque_FichaEstoque.pas' {Impressao_Estoque_FichaEstoque},
  frmImpressao_FiscaisOP_Inventario_P7 in 'frmImpressao_FiscaisOP_Inventario_P7.pas' {Impressao_FiscaisOP_Inventario_P7},
  frmCadastro_CodigosRFB in 'frmCadastro_CodigosRFB.pas' {Cadastro_CodigosRFB},
  frmCadastro_Majoracao in 'frmCadastro_Majoracao.pas' {Cadastro_Majoracao},
  frmFiscal_BloquearPeriodo in 'frmFiscal_BloquearPeriodo.pas' {Fiscal_BloquearPeriodo},
  frmFiscal_SaldoICMSIPI in 'frmFiscal_SaldoICMSIPI.pas' {Fiscal_SaldoICMSIPI},
  frmCadastro_PCTerceirosClientes in 'frmCadastro_PCTerceirosClientes.pas' {Cadastro_PCTerceirosClientes},
  frmCadastro_PCTerceirosProc in 'frmCadastro_PCTerceirosProc.pas' {Cadastro_PCTerceirosProc},
  frmCadastro_PCTerceirosForn in 'frmCadastro_PCTerceirosForn.pas' {Cadastro_PCTerceirosForn},
  frmFichaEstoque in 'frmFichaEstoque.pas' {FichaEstoque},
  frmDetectaCaracterXML in 'frmDetectaCaracterXML.pas' {DetectaCaracterXML},
  frmFichaInventario in 'frmFichaInventario.pas' {FichaInventario},
  frmPedido_ItensDividir in 'frmPedido_ItensDividir.pas' {Pedido_ItensDividir},
  frmImpressao_Estoque_Seriais in 'frmImpressao_Estoque_Seriais.pas' {Impressao_Estoque_Seriais},
  frmImpressao_FiscaisOP_LivroServicoTomado in 'frmImpressao_FiscaisOP_LivroServicoTomado.pas' {Impressao_FiscaisOP_LivroServicoTomado},
  frmExportar_ArmazemNFSai in 'frmExportar_ArmazemNFSai.pas' {Exportar_ArmazemNFSai},
  frmImpressao_Estoque_FichaInventario in 'frmImpressao_Estoque_FichaInventario.pas' {Impressao_Estoque_FichaInventario},
  frmPedido_ItensOutrosRateioLucro in 'frmPedido_ItensOutrosRateioLucro.pas' {Pedido_ItensOutrosRateioValor},
  frmProcesso_Invoice in 'frmProcesso_Invoice.pas' {Processo_Invoice},
  frmProcesso_InvoiceExportacao in 'frmProcesso_InvoiceExportacao.pas' {Processo_InvoiceExportacao},
  frmImpressao_ProcessosOP_PackingList in 'frmImpressao_ProcessosOP_PackingList.pas' {Impressao_ProcessosOP_PackingList},
  frmFiscal_GNRE in 'frmFiscal_GNRE.pas' {Fiscal_GNRE},
  frmImpressao_FiscaisOP_DIFAL in 'frmImpressao_FiscaisOP_DIFAL.pas' {Impressao_FiscaisOP_DIFAL},
  frmUtilitarios_AjustarItem in 'frmUtilitarios_AjustarItem.pas' {Utilitarios_AjustarItem},
  frmCadastro_ProdutosMateriaPrima in 'frmCadastro_ProdutosMateriaPrima.pas' {Cadastro_ProdutosMateriaPrima},
  frmCadastro_DRE in 'frmCadastro_DRE.pas' {Cadastro_DRE},
  frmUtilitarios_ImportarSISCOMEXWEBXML in 'frmUtilitarios_ImportarSISCOMEXWEBXML.pas' {Utilitarios_ImportarSISCOMEXWEBXML},
  frmCadastro_ClassificacaoFiliais in 'frmCadastro_ClassificacaoFiliais.pas' {Cadastro_ClassificacaoFiliais},
  frmCadastro_PlanoContasECF in 'frmCadastro_PlanoContasECF.pas' {Cadastro_PlanoContasECF},
  frmCadastro_PlanoContasECFRelac in 'frmCadastro_PlanoContasECFRelac.pas' {Cadastro_PlanoContasECFRelac},
  frmImpressao_Faturamento_ComposicaoNF in 'frmImpressao_Faturamento_ComposicaoNF.pas' {Impressao_Faturamento_ComposicaoNF},
  frmImpressao_ProcessosOP_Proforma in 'frmImpressao_ProcessosOP_Proforma.pas' {Impressao_ProcessosOP_Proforma},
  frmContabilidade_Exclusao in 'frmContabilidade_Exclusao.pas' {Contabilidade_Exclusao},
  frmContabilidade_BloquearPeriodo in 'frmContabilidade_BloquearPeriodo.pas' {Contabilidade_BloquearPeriodo},
  frmUtilitarios_ExportaSPED_ECD in 'frmUtilitarios_ExportaSPED_ECD.pas' {Utilitarios_ExportaSPED_ECD},
  frmImpressao_FinanceirosOP_ExtratoBanco in 'frmImpressao_FinanceirosOP_ExtratoBanco.pas' {Impressao_FinanceirosOP_ExtratoBanco},
  frmProforma_Itens in 'frmProforma_Itens.pas' {Proforma_Itens},
  frmCadastro_NCMConsultaTEC in 'frmCadastro_NCMConsultaTEC.pas' {Cadastro_NCMConsultaTEC},
  frmCadastro_NCMAtualizaTEC in 'frmCadastro_NCMAtualizaTEC.pas' {Cadastro_NCMAtualizaTEC},
  frmProforma_ItensImportar in 'frmProforma_ItensImportar.pas' {Proforma_ItensImportar},
  frmProforma_ItensImportarQtde in 'frmProforma_ItensImportarQtde.pas' {Proforma_ItensImportarQtde},
  frmContabilidade_LanEncerramento in 'frmContabilidade_LanEncerramento.pas' {Contabilidade_LanEncerramento},
  frmCadastro_ProdutosSeriaisNotas in 'frmCadastro_ProdutosSeriaisNotas.pas' {Cadastro_ProdutosSeriaisNotas},
  frmImpressao_FinanceirosOP_ExtratoBancoSint in 'frmImpressao_FinanceirosOP_ExtratoBancoSint.pas' {Impressao_FinanceirosOP_ExtratoBancoSint},
  frmCadastro_DREContabil in 'frmCadastro_DREContabil.pas' {Cadastro_DREContabil},
  frmContabilidade_LancamentosDiferenca in 'frmContabilidade_LancamentosDiferenca.pas' {Contabilidade_LancamentosDiferenca},
  frmCadastro_NCMProdutos in 'frmCadastro_NCMProdutos.pas' {Cadastro_NCMProdutos},
  frmImpressao_ContabeisOP_DRE in 'frmImpressao_ContabeisOP_DRE.pas' {Impressao_ContabeisOP_DRE},
  frmUtilitarios_Importar_NFe_TerceirosSeriais in 'frmUtilitarios_Importar_NFe_TerceirosSeriais.pas' {Utilitarios_Importar_NFe_TerceirosSeriais},
  frmNotaFiscal_TerceirosAlteraChassi in 'frmNotaFiscal_TerceirosAlteraChassi.pas' {NotaFiscal_TerceirosAlteraChassi},
  frmFinanceiro_ControleCheques in 'frmFinanceiro_ControleCheques.pas' {Financeiro_ControleCheques},
  frmUtilitarios_Importar_NFe_TerceirosLotes in 'frmUtilitarios_Importar_NFe_TerceirosLotes.pas' {Utilitarios_Importar_NFe_TerceirosLotes},
  frmPedido_ItensOutrosDetalhe in 'frmPedido_ItensOutrosDetalhe.pas' {Pedido_ItensOutrosDetalhe},
  frmImpressao_FinanceirosOP_Cheques in 'frmImpressao_FinanceirosOP_Cheques.pas' {Impressao_FinanceirosOP_Cheques},
  frmProcesso_ImportacaoDespesas in 'frmProcesso_ImportacaoDespesas.pas' {Processo_ImportacaoDespesas},
  frmUtilitarios_Importar_NFe_TerceirosRastrearSeriais in 'frmUtilitarios_Importar_NFe_TerceirosRastrearSeriais.pas' {Utilitarios_Importar_NFe_TerceirosRastrearSeriais},
  frmPedidosOutra_LoteItens in 'frmPedidosOutra_LoteItens.pas' {PedidosOutra_LoteItens},
  frmUtilitarios_Script in 'frmUtilitarios_Script.pas' {Utilitarios_Script},
  frmFinanceiro_Agendamento in 'frmFinanceiro_Agendamento.pas' {Financeiro_Agendamento},
  NFe_Util_2G_TLB in 'NFe_Util_2G_TLB.pas',
  frmPedido_EndEntregaRetirada in 'frmPedido_EndEntregaRetirada.pas' {Pedido_EndEntregaRetirada},
  frmCTEPasta in 'frmCTEPasta.pas' {CTePasta},
  frmProcesso_PLI in 'frmProcesso_PLI.pas' {Processo_PLI},
  DITransmissao in 'DITransmissao.pas',
  frmDMDespacho in 'frmDMDespacho.pas' {dmDespacho: TDataModule},
  frmPesquisaGerais in 'frmPesquisaGerais.pas' {PesquisaGerais},
  frmProcesso_PO in 'frmProcesso_PO.pas' {Processo_PO},
  frmJanela_Imagem in 'frmJanela_Imagem.pas' {Janela_Imagem},
  frmUtilitarios_ImportarXML in 'frmUtilitarios_ImportarXML.pas' {Utilitarios_ImportarXML},
  frmUtilitarios_LayoutXMLNFS in 'frmUtilitarios_LayoutXMLNFS.pas' {Utilitarios_ImportarXML},
  frmPedido_CTEComp in 'frmPedido_CTEComp.pas' {Pedido_CTEComp},
  frmCadastros_TaxaSISCOMEX in 'frmCadastros_TaxaSISCOMEX.pas' {Cadastro_TaxaSISCOMEX},
  frmImpressao_ProcessosOP_PO in 'frmImpressao_ProcessosOP_PO.pas' {Impressao_ProcessosOP_PO},
  frmProcesso_POImportaItens in 'frmProcesso_POImportaItens.pas' {Processo_POImportaItens},
  frmFiscal_ProcessosREINF in 'frmFiscal_ProcessosREINF.pas' {Fiscal_ProcessosREINF},
  frmFichaEstoque2 in 'frmFichaEstoque2.pas' {FichaEstoque2},
  frmImpressao_Estoque_TabelaPreco in 'frmImpressao_Estoque_TabelaPreco.pas' {Impressao_Estoque_TabelaPreco},
  frmPedidosOutra_ProprioReferenciaItens in 'frmPedidosOutra_ProprioReferenciaItens.pas' {PedidosOutra_ProprioReferenciaItens},
  frmFinanceiro_ImpostosMes in 'frmFinanceiro_ImpostosMes.pas' {Financeiro_ImpostosMes},
  frmNotaFiscal_ServicoItens in 'frmNotaFiscal_ServicoItens.pas' {NotaFiscal_Servicoitens},
  frmPedidosOutra_TerceirosReferenciaItens in 'frmPedidosOutra_TerceirosReferenciaItens.pas' {PedidosOutra_TerceirosReferenciaItens},
  frmImpressao_Fiscais_ApuracaoICMSRecuperar in 'frmImpressao_Fiscais_ApuracaoICMSRecuperar.pas' {Impressao_Fiscais_ApuracaoICMSRecuperar},
  frmImpressao_ProcessosOP_Proposta in 'frmImpressao_ProcessosOP_Proposta.pas' {Impressao_ProcessosOP_Proposta},
  frmProposta_Exportacao in 'frmProposta_Exportacao.pas' {Proposta_Exportacao},
  frmPedidosRepresentantes_Financeiro in 'frmPedidosRepresentantes_Financeiro.pas' {PedidosRepresentantes_Financeiro},
  frmFinanceiro_PedidosRepresentantesSite in 'frmFinanceiro_PedidosRepresentantesSite.pas' {Financeiro_PedidosRepresentantesSite},
  frmCadastro_LancamentoPadrao in 'frmCadastro_LancamentoPadrao.pas' {Cadastro_LancamentoPadrao},
  frmFinanceiro_PagamentosMes in 'frmFinanceiro_PagamentosMes.pas' {Financeiro_PagamentosMes},
  frmPedido_Compra in 'frmPedido_Compra.pas' {Pedido_Compra},
  frmPedido_CompraItens in 'frmPedido_CompraItens.pas' {Pedido_CompraItens},
  frmCadastro_Intermediarios in 'frmCadastro_Intermediarios.pas' {Cadastro_Intermediarios},
  Vcl.Consts in 'Vcl.Consts.pas' {ConsultaCEP in 'ConsultaCEP.pas'},
  frmImpressao_FinanceirosOP_PagarReceber_New in 'frmImpressao_FinanceirosOP_PagarReceber.pas' {Impressao_FinanceirosOP_PagarReceber},
  ConsultaCEP in 'ConsultaCEP.pas' {ConsultaCEP in 'ConsultaCEP.pas'},
  frmProcesso_DUE in 'frmProcesso_DUE.pas' {Processo_DUE},
  frmUtilitarios_OutrosDesativar in 'frmUtilitarios_OutrosDesativar.pas' {Utilitarios_OutrosDesativar},
  frmUtilitarios_Exportar_Armazem in 'frmUtilitarios_Exportar_Armazem.pas' {Utilitarios_Exportar_Armazem},
  frmUtilitarios_Exportar_ArmazemPed in 'frmUtilitarios_Exportar_ArmazemPed.pas' {Utilitarios_Exportar_ArmazemPed},
  frmUtilitarios_ImportarPlanoContasRef in 'frmUtilitarios_ImportarPlanoContasRef.pas' {Utilitarios_ImportarPlanoContasRef},
  frmImpressao_Faturamento_Analitico in 'frmImpressao_Faturamento_Analitico.pas' {Impressao_Faturamento_Analitico},
  frmUtilitarios_RecriarContabil2 in 'frmUtilitarios_RecriarContabil2.pas' {Utilitarios_RecriarContabil2},
  frmUtilitarios_RecriarContabil in 'frmUtilitarios_RecriarContabil.pas' {Utilitarios_RecriarContabil},
  frmDespacho_LI in 'frmDespacho_LI.pas' {Despacho_LI},
  frmProcesso_InvoiceItens in 'frmProcesso_InvoiceItens.pas' {Processo_InvoiceItens},
  frmInvoice_ItensQtde in 'frmInvoice_ItensQtde.pas' {Invoice_ItensQtde},
  frmPedido_RepresentantesSimp in 'frmPedido_RepresentantesSimp.pas' {Pedido_RepresentantesSimp},
  frmPedido_RepresentanteAltera in 'frmPedido_RepresentanteAltera.pas' {Pedido_RepresentanteAltera},
  frmCadastro_PlanoContasAnterior in 'frmCadastro_PlanoContasAnterior.pas' {Cadastro_PlanoContasAnterior},
  frmPedido_RepresentanteDevolucao in 'frmPedido_RepresentanteDevolucao.pas' {Pedido_RepresentanteDevolucao},
  frmImpressao_Estoque_SeriaisSit in 'frmImpressao_Estoque_SeriaisSit.pas' {Impressao_Estoque_SeriaisSit},
  frmProcesso_SimulacaoMercante in 'frmProcesso_SimulacaoMercante.pas' {Processo_SimulacaoMercante},
  frmPedidosRepresentantes_FiltroFat in 'frmPedidosRepresentantes_FiltroFat.pas' {PedidosRepresentantes_FiltroFat},
  frmFinanceiro_PedidosRepAutorizacao in 'frmFinanceiro_PedidosRepAutorizacao.pas' {Financeiro_PedidosRepAutorizacao},
  frmProcesso_ControleNavios in 'frmProcesso_ControleNavios.pas' {Processo_ControleNavios},
  frmPedidosRepresentantes_Parcial in 'frmPedidosRepresentantes_Parcial.pas' {PedidosRepresentantes_Parcial},
  frmCadastro_RecapPadrao in 'frmCadastro_RecapPadrao.pas' {Cadastro_RecapPadrao},
  frmPedido_TelevendasItensComb in 'frmPedido_TelevendasItensComb.pas' {Pedido_TelevendasItensComb},
  frmNotaFiscal_ServicoXML in 'frmNotaFiscal_ServicoXML.pas' {NotaFiscal_ServicoXML},
  frmUtilitarios_AjustarEstoqueNavio in 'frmUtilitarios_AjustarEstoqueNavio.pas' {Utilitarios_AjustarEstoqueNavio},
  frmPedido_RepresentanteVeiculo in 'frmPedido_RepresentanteVeiculo.pas' {Pedido_RepresentanteVeiculo},
  frmImpressao_ProcessosOP_Navio in 'frmImpressao_ProcessosOP_Navio.pas' {Impressao_ProcessosOP_Navio},
  frmBuscarXMLTerceiros in 'frmBuscarXMLTerceiros.pas' {BuscarXMLTerceiros},
  frmNotaFiscal_TerceirosCredito in 'frmNotaFiscal_TerceirosCredito.pas' {NotaFiscal_TerceirosCredito},
  frmControleNaviosLaudoBL in 'frmControleNaviosLaudoBL.pas' {ControleNaviosLaudoBL},
  frmImpressao_OP_FaturamentoRecebimento in 'frmImpressao_OP_FaturamentoRecebimento.pas' {Impressao_OP_FaturamentoRecebimento},
  frmImpressao_ProcessosOP_LimiteRADAR in 'frmImpressao_ProcessosOP_LimiteRADAR.pas' {Impressao_ProcessosOP_LimiteRADAR},
  frmImpressao_ControleNavios in 'frmImpressao_ControleNavios.pas' {Impressao_ControleNavios},
  frmImpressao_ControleNaviosBL in 'frmImpressao_ControleNaviosBL.pas' {Impressao_ControleNaviosBL},
  frmImpressao_ControleNaviosLaudo in 'frmImpressao_ControleNaviosLaudo.pas' {Impressao_ControleNaviosLaudo},
  frmUtilitarios_ImportarAPIPUCOMEX in 'frmUtilitarios_ImportarAPIPUCOMEX.pas' {Utilitarios_ImportarAPIPUCOMEX},
  frmImpressao_ControleNaviosNotas in 'frmImpressao_ControleNaviosNotas.pas' {Impressao_ControleNaviosNotas},
  frmCTE_PrestacaoDesacordo in 'frmCTE_PrestacaoDesacordo.pas' {CTE_PrestacaoDesacordo},
  CTe_Util_TLB in 'C:\Users\Ded\Documents\Embarcadero\Studio\20.0\Imports\CTe_Util_TLB.pas',
  Vcl.Themes,
  Vcl.Styles,
  frmImpressao_Financeiros_FluxoCaixaDetalhado2 in 'frmImpressao_Financeiros_FluxoCaixaDetalhado2.pas' {Impressao_Financeiros_FluxoCaixaDetalhado2},
  frmImpressao_Faturamento_HistoricoPedidos in 'frmImpressao_Faturamento_HistoricoPedidos.pas' {Impressao_Faturamento_HistoricoPedidos},
  frmImpressao_ProcessosOP_Armazem in 'frmImpressao_ProcessosOP_Armazem.pas' {Impressao_ProcessosOP_Armazem},
  frmCadastro_NCMAtributos in 'frmCadastro_NCMAtributos.pas' {Cadastro_NCMAtributos},
  frmImpressao_Faturamento_VendasClientes in 'frmImpressao_Faturamento_VendasClientes.pas' {Impressao_Faturamento_VendasClientes},
  frmCadastro_ProdutosAtributos in 'frmCadastro_ProdutosAtributos.pas' {Cadastro_ProdutosAtributos},
  frmFinanceiro_NFCancelada in 'frmFinanceiro_NFCancelada.pas' {Financeiro_NFCancelada},
  frmImpressao_GeraisOP_DMI in 'frmImpressao_GeraisOP_DMI.pas' {Impressao_GeraisOP_DMI},
  frmConfig_ReferenciaFiliais in 'frmConfig_ReferenciaFiliais.pas' {Config_ReferenciaFiliais},
  frmPedido_ServicoXML in 'frmPedido_ServicoXML.pas' {Pedido_ServicoXML},
  frmImpressao_Financeiros_ContBoletos in 'frmImpressao_Financeiros_ContBoletos.pas' {Impressao_Financeiros_ContBoletos},
  frmPedidosRepresentantes_PedidoNF in 'frmPedidosRepresentantes_PedidoNF.pas' {PedidosRepresentantes_PedidoNF2},
  frmPedidosRepresentantes_PedidoNF2 in 'frmPedidosRepresentantes_PedidoNF2.pas' {PedidosRepresentantes_PedidoNF2},
  Frm_ACBrReinf in 'Frm_ACBrReinf.pas' {frmACBrReinf},
  frmNotaFiscal_ServicoVinculo in 'frmNotaFiscal_ServicoVinculo.pas' {NotaFiscal_ServicoVinculo},
  frmNotaFiscal_TerceirosVinculo in 'frmNotaFiscal_TerceirosVinculo.pas' {NotaFiscal_TerceirosVinculo},
  frmImpressao_Estoque_MediaVendas in 'frmImpressao_Estoque_MediaVendas.pas' {Impressao_Estoque_MediaVendas},
  frmCadastro_ProdutosFiliais in 'frmCadastro_ProdutosFiliais.pas' {Cadastro_ProdutosFiliais},
  frmCadastro_Usuarios2 in 'frmCadastro_Usuarios2.pas' {Cadastro_Usuarios2},
  frmUtilitario_ExportaAPI in 'frmUtilitario_ExportaAPI.pas' {Utilitario_ExportaAPI},
  frmPedido_TelevendasCatalogo in 'frmPedido_TelevendasCatalogo.pas' {Pedido_TelevendasCatalogo},
  frmPedido_TelevendasCatalogoItem in 'frmPedido_TelevendasCatalogoItem.pas' {Pedido_TelevendasCatalogoItem},
  frmNFE50 in 'frmNFE50.pas' {NFE50},
  frmImpressao_FinanceirosOP_PagarReceberSimp in 'frmImpressao_FinanceirosOP_PagarReceberSimp.pas' {Impressao_FinanceirosOP_PagarReceberSimp},
  frmFinanceiro_EmprestimosDDData in 'frmFinanceiro_EmprestimosDDData.pas' {Financeiro_EmprestimosDDData},
  frmImpressao_FinanceirosOP_ControleAbertos in 'frmImpressao_FinanceirosOP_ControleAbertos.pas' {Impressao_FinanceirosOP_ControleAbertos},
  frmProcesso_DUIMP in 'frmProcesso_DUIMP.pas' {Processo_DUIMP},
  frmProcesso_RegistroDI in 'frmProcesso_RegistroDI.pas' {Processo_RegistroDI},
  frmCadastro_LPCO in 'frmCadastro_LPCO.pas' {Cadastro_LPCO},
  frmProcesso_InvoiceLPCO in 'frmProcesso_InvoiceLPCO.pas' {Processo_InvoiceLPCO},
  frmIndustrializacao in 'frmIndustrializacao.pas' {Industrializacao},
  frmPedido_NFS in 'frmPedido_NFS.pas' {Pedido_NFS},
  frmPedido_NFSItens in 'frmPedido_NFSItens.pas' {Pedido_NFSItens},
  frmPedido_NFSVinculo in 'frmPedido_NFSVinculo.pas' {Pedido_NFSVinculo};

{$R *.res}

begin
  // Mostrando a tela de Splash Screen.
  Splash_Screen := TSplash_Screen.Create(Application);
  Splash_Screen.Show;
  Splash_Screen.Update;
  Sleep(2000);
  Splash_Screen.Hide;

  Application.Initialize;

  TStyleManager.TrySetStyle('Cyber001C');
  Application.Title := 'Cybersoft ERP Importa';
  Application.CreateForm(TMenu_Principal, Menu_Principal);
  Application.CreateForm(TDados, Dados);
  Application.CreateForm(TdmImporta, dmImporta);
  Application.CreateForm(TdmContab, dmContab);
  Application.CreateForm(TdmFiscal, dmFiscal);
  Application.CreateForm(TdmComercial, dmComercial);
  Application.CreateForm(TdmDespacho, dmDespacho);
  Application.Run;
end.








